### ISSUE TITLE
Alpha Status

### ISSUE THREAD

**Issue by ToddThomson** [Achilles-Software/Entities.Sqlite#1]
These are the tasks that we are working on before moving to a first beta release

Alpha Tasks to Complete:

Mapping
- [x] Support column mapping for Properties and Fields

Modelling
- [x] Add Relationship fluent  mapping: HasOne and HasMany ( Issue #6 )

Querying

- [x] Rename DbTableX to EntityX and reorg Linq provider code
- [x] Add complete async queryable methods ( Issue #2 )
- [x] Support Lazy/OnDemand loading ( Issue #12 )
- [ ] Support Eager loading for related properties ( Issue  #14 )
- [x] Support Projections ( Issue  #15 )

Documentation
- [x] Document public API (c# XML)
- [x] Add Wiki and additional project documentation
- [x] Update license to include all referenced sources and authors

**Comment by ToddThomson** [comment]
Async CRUD tests added. ToListAsync failing. Insert, Update, Delete working.

EDIT: Completed

**Comment by ToddThomson** [comment]
ToListAsync method has been added in Nuget package 0.1.6-alpha.

The sample TodoApp now builds and runs on the Android emulator.

**Comment by ToddThomson** [comment]
Dev branch commit 0.2.0-alpha. Progress towards beta release (must remember to reference this issue during commits to self document updates ).
